### ISSUE TITLE
Release ARM64 agent version

### ISSUE THREAD

**Issue by 3asm** [Ostorlab/oxo#312]
Users on Mac with M1 require ARM64 images. We currently only support and release x64 images which require a compatibility runtime.

Adding this requires multi-dockerfile support and agent builders supporting ARM64.

**Comment by jamu85** [comment]
I currently do not understand the DevOps you are using to build the images but maybe I can help.

As you use the build-push-action which uses buildx, multi platform builds could be made by this action if setup like bellow.
```
        ...
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: user/app:latest
         ...
```
However, I see that the GitHub actions workflows for the docker build, in the agent repositories are all commented. So I'm not sure how the builds are made.
Regarding the Dockerfile we might be able to build all architectures from one file.

How are the image builds currently implemented?
